firstName: 1
lastName: 2
emailId: 3
address: 4
phoneNumber: 5
gender: 6
category: 7
relativeName: 8
parentsOccupation: 9
aadharNumber: 10
noOfEarningFamilyMembers: 11
totalHouseholdIncome: 12
ownGadget: 13
courseName: 14
collegeName: 15
completedAcademicYear: 16
about: 17
areaOfInterest: 18
hoursAllocation: 19