firstName: 0
lastName: 1
emailId: 2
address: 3
phoneNumber: 4
gender: 5
category: 6
relativeName: 7
parentsOccupation: 8
aadharNumber: 9
noOfEarningFamilyMembers: 10
totalHouseholdIncome: 11
ownGadget: 12
courseName: 13
collegeName: 14
completedAcademicYear: 15
about: 16
areaOfInterest: 17
hoursAllocation: 18